### ISSUE TITLE
Importing private keys with scsh

### ISSUE THREAD

**Issue by OYTIS** [CardContact/scsh-scripts#2]
Hi,
I'm trying to import a private key to a CardContact-based smartcard (namely, Nitrokey HSM). As far as I understand just writing data using just pkcs11-tool was disabled for security reasons, so I did the whole procedure of generating TLS credentials, connecting to CardContact server and downloading the SDK.
Now when I feed my *.p12 to importP12.js from scsh3gui I get the following error:

```
org.mozilla.javascript.EcmaError: TypeError: Cannot read property "length" from undefined (/home/oytis/Downloads/sc-hsm-sdk/sc-hsm-workspace/scsh/sc-hsm/DKEK.js#80)
    at /home/oytis/Downloads/sc-hsm-sdk/sc-hsm-workspace/scsh/sc-hsm/DKEK.js#80
    at /home/oytis/Downloads/sc-hsm-sdk/sc-hsm-workspace/sc-hsm-sdk-scripts/key_import/import_P12.js#115
```
Any idea why this can take place? I use scsh v 3.13.292 and sc-hsm-workspace v 20160930.

Thanks!

**Comment by CardContact** [comment]
The recommended (and probably easier way) is to use the Key Manager available as part of a recent Smart Card Shell.

Just press CTRL-M to start the key manager and select "Import from PKCS#11 file" a the top-level node in the outline.

The SmartCard-HSM needs to be initialized with a DKEK and you will need to install the unrestricted cryptographic strength policy for the Java VM (The import process uses AES-256 which is not enabled by default).

**Comment by OYTIS** [comment]
@CardContact Thank you.
But I get a somewhat similar error using this method.

```
Importing key and certificate...
org.mozilla.javascript.EcmaError: TypeError: Cannot read property "length" from undefined (/home/oytis/Downloads/smartcardshell/scsh3.13.292/scsh/sc-hsm/DKEK.js#268)
    at /home/oytis/Downloads/smartcardshell/scsh3.13.292/scsh/sc-hsm/DKEK.js#268
    at /home/oytis/Downloads/smartcardshell/scsh3.13.292/keymanager/keymanager.js#1365
    at /home/oytis/Downloads/smartcardshell/scsh3.13.292/keymanager/keymanager.js#1509
```

**Comment by CardContact** [comment]
Are you importing a RSA key ?

**Comment by OYTIS** [comment]
As far as I understand it's an RSA key stored in PKCS#8 format (PEM dump begins with '-----BEGIN PRIVATE KEY-----')

**Comment by OYTIS** [comment]
No, sorry, it's ECDSA.

**Comment by CardContact** [comment]
Unfortunately importing ECDSA keys is currently not supported.

The SmartCard-HSM has the ability to do that, but the DKEK.js class can not encode the required format. There was just no request for it yet.

**Comment by OYTIS** [comment]
Is it possible to use another function, importKey? It requires a wrapped key, maybe I can wrap mine somehow? It seems to be quite ignorant of the key internals.

**Comment by CardContact** [comment]
The DKEK.js available in the scsh-mods repo on CDN has now support for ECC keys. There is also an updated keymanager.js to import ECC private key and certifictate from PKCS#12.

Both modules will be available in the next SCSH3 release.
