### ISSUE TITLE
[RFE] Document wrapped format/Import EC keys

### ISSUE THREAD

**Issue by aalba6675** [CardContact/scsh-scripts#3]
For migration of legacy systems (soft private keys) it is useful to import EC keys. 

#2 states that we can already import RSA keys. I would like to RFE

Either 
1. Document wrap format so we may import EC keys
2. Enhance DKEK.js to import EC keys

I acknowledge CardContact  position that this defeats the purpose of having a HSM and on-chip key generation. However this feature is necessary to migrate legacy systems.

**Comment by CardContact** [comment]
The latest DKEK.js module in the CDN repo as well as the latest keymanager.js support ECC keys. This will be included in the next SCSH3 release.

For early access, you can clone the scsh-mods and sc-hsm-sdk-scripts repo from CDN.

**Comment by aalba6675** [comment]
Noted - with thanks - and closing.
