### ISSUE TITLE
Cannot import PKCS#12-formatted file into Nitrokey HSM

### ISSUE THREAD

**Issue by fladna9** [CardContact/scsh-scripts#4]
Hi, 

I don't know if i'm posting this issue in the right place, i'm sorry if it's not the case.

i'm having a problem importing a PKCS#12-formatted file using the SCSH v3.14.268 on macOS using the GUI 'Key Manager' feature (right-click, etc.)

**My setup:**
- A Nitrokey HSM, freshly updated (to V2.6 for issuer DEDINK0200001 via http://www.pki-as-a-service.net/cardcontact ) and initialized (and already few keys on it),
- Initialized with 1 DKEK Share key and strong random password (32 alphanumeric chars),
- A macOS KeyStore-generated PKCS#12 file I want to import.

**Expected:** 
When setting everything correctly in the GUI (ie. 1 DKEK, path to correct DKEK, passphrase), it should ask and import my PKCS#12 keys and certificates into the HSM

**What's happening:**
After setting everything correctly in the GUI (ie. 1 DKEK, path to correct DKEK, passphrase), i have this console output:
```
Derive DKEK share encryption key (Step 1 of 3)...
Derive DKEK share encryption key (Step 2 of 3)...
Derive DKEK share encryption key (Step 3 of 3)...
GPError: Crypto (CRYPTO_FAILED/51) - "Illegal key size" in /Users/fladnag/Downloads/scsh3.14.348/scsh/sc-hsm/DKEK.js#213
    at /Users/fladnag/Downloads/scsh3.14.348/scsh/sc-hsm/DKEK.js#213
    at /Users/fladnag/Downloads/scsh3.14.348/keymanager/keymanager.js#1821
    at /Users/fladnag/Downloads/scsh3.14.348/keymanager/keymanager.js#2028
```
It seems it can't decipher the DKEK.

Do you have an idea about the problem I have ?

**Comment by CardContact** [comment]
You need to install the JCE Unlimited Strength Jurisdiction Policy in your Java-VM available at 

https://www.oracle.com/technetwork/java/javase/downloads/jce8-download-2133166.html

to make AES-256 work.

**Comment by fladna9** [comment]
Thanks for the tip, it was done on the wrong version.
Closing this issue, have a nice day.
