### ISSUE TITLE
Cannot import EC-256 key pair in P12 format

### ISSUE THREAD

**Issue by rogerlucas-veea** [CardContact/scsh-scripts#6]
Hi All,

I'm running the latest 3.15.288 scsh with a CardContact 4K token which is labelled as "uTrust Token Standard".  The platform is Ubuntu 18.04 and openjdk v11.0.4, which is the default for the platform.

I have existing EC-256 keys that I would like to import and protect in the token so that I can give the token to someone else so that they can use the keys but not see them or copy them elsewhere.

I converted the existing PEM files to a P12 file using OpenSSL and the command:

`openssl pkcs12 -export -out keypair.p12 -inkey key_priv.pem -in key_cert.pem`

I created a DKEK with single share in scsh3gui, so far, so good.

When I try to import the P12 file, I provide the DKEK then the P12 file and I get an error:

Derive DKEK share encryption key (Step 1 of 3)...
Derive DKEK share encryption key (Step 2 of 3)...
Derive DKEK share encryption key (Step 3 of 3)...

<< Here it prints the certificate information >>

Importing key and certificate...
GPError: Card (CARD_INVALID_SW/27904) - "Unexpected SW1/SW2=6D00 (Checking error: Invalid instruction (0)) received" in /home/labuser/workspace/cardcontact/scsh3.15.388/scsh/sc-hsm/SmartCardHSM.js#1270
    at /home/labuser/workspace/cardcontact/scsh3.15.388/scsh/sc-hsm/SmartCardHSM.js#1270
    at /home/labuser/workspace/cardcontact/scsh3.15.388/scsh/sc-hsm/HSMKeyStore.js#333
    at /home/labuser/workspace/cardcontact/scsh3.15.388/keymanager/keymanager.js#1934
    at /home/labuser/workspace/cardcontact/scsh3.15.388/keymanager/keymanager.js#2085

Do you have any suggestions what the problem may be and how I can resolve it?

Many thanks.

**Comment by CardContact** [comment]
Error code 6D00 indicates, that the device was not initialized with a DKEK.

The DKEK needs to be present at two different stages: During initialization of the device and when importing a key. During initialization the DKEK is imported. During import the DKEK is used to encrypt the key blob for import into the device.

Select "DKEK Shares" in the "Select Device Key Encryption Scheme" in one of the configuration dialog during initialization. Then after initialization, right-click on "DKEK set-up in progress with 1 of 1 share missing"  and select "Import DKEK share". Once you have done this, retry the import from PKCS#12 file.

**Comment by rogerlucas-veea** [comment]
@CardContact Thank you for the quick response.  I re-initialised the token with a DKEK and it's now working.
